<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])
    ->group(function () {
        Route::get(
            '/products',
            App\Livewire\Dashboard\ProductIndex::class
        )->name('products.index');

        Route::get(
            '/products/create',
            App\Livewire\Dashboard\ProductCreate::class
        )->name('products.create');

        Route::get(
            '/products/{product}',
            App\Livewire\Dashboard\ProductEdit::class
        )->name('products.edit');

        Route::get(
            '/categories',
            App\Livewire\Dashboard\CategoryIndex::class
        )->name('categories.index');

        Route::get(
            '/categories/create',
            App\Livewire\Dashboard\CategoryCreate::class
        )->name('categories.create');

        Route::get(
            '/categories/{category}',
            App\Livewire\Dashboard\CategoryEdit::class
        )->name('categories.edit');
    });

// Site
Route::prefix('/')->group(function () {});

// Admin
Route::prefix('/admin')
    ->name('admin.')
    ->group(function () {});
